"""Report generator producing professional reports with traceable citations."""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path
from app.models.schemas import ResearchReport
from app.config import config

class ReportGenerator:
    def render_markdown(self, report: ResearchReport) -> str:
        timestamp_str = report.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")
        md_lines = [f"# Academic Research Report: {report.research_question}", f"\n*Generated by Lightweight Academic Research Agent on {timestamp_str}*\n", "---\n",
            "## 1. Research Question", f"> **{report.research_question}**\n", "## 2. Executive Summary", f"{report.executive_summary}\n",
            "## 3. Research Methodology", f"{report.research_methodology}\n", "## 4. Academic Sources Searched", "The following independent academic sources and registries were queried:"]
        md_lines.extend(f"- **{src.replace('_', ' ').title()}**" for src in report.academic_sources_searched)
        md_lines.extend(["", "## 5. Search Strategy", f"{report.search_strategy_summary}\n", "## 6. Key Findings"])
        md_lines.extend(f"{idx}. {finding}" for idx, finding in enumerate(report.key_findings, 1))
        md_lines.extend(["", "## 7. Evidence Table", "| Evidence ID | Claim ID | Paper ID | Evidence Type | Strength | Section | Pages | Full Text | Extracted Excerpt |", "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |"])
        for ev in report.evidence_records:
            excerpt = ev.quote_or_excerpt.replace("|", "\\|")
            if len(excerpt) > 90: excerpt = excerpt[:87] + "..."
            pages = f"{ev.page_start}-{ev.page_end}" if ev.page_start else "—"
            grounded = "YES" if ev.full_text_grounded else "NO — ABSTRACT-ONLY"
            md_lines.append(f"| {ev.evidence_id} | {ev.claim_id} | [{ev.paper_id}] | {ev.evidence_type.value} | `{ev.strength.value}` | {ev.section} | {pages} | {grounded} | {excerpt} |")
        if not report.evidence_records: md_lines.append("| — | — | — | — | — | — | — | — | No specific evidence records captured |")
        md_lines.extend(["", "## 8. Supporting Evidence"])
        for c in report.claims:
            srcs = ", ".join(f"[{s}]" for s in c.supporting_sources) or f"[{c.paper_id}]"
            provenance = "FULL-TEXT" if c.section != "abstract" else "ABSTRACT-ONLY"
            md_lines.append(f"- **Claim ({c.evidence_type.value}; {provenance})**: {c.claim_text}")
            md_lines.append(f"  - **Sources**: {srcs} | **Section**: {c.section} | **Pages**: {c.page_start or '—'}-{c.page_end or '—'} | **Strength**: `{c.evidence_strength.value}` | **Confidence**: {c.confidence:.2f}")
        md_lines.extend(["", "## 9. Contradictory Evidence & Scientific Disagreements", "| Technical Point / Claim | Supporting Papers | Contradicting / Caveat Papers | Overall Assessment |", "| :--- | :--- | :--- | :--- |"])
        for contra in report.contradictions:
            md_lines.append(f"| {contra.claim.replace('|','\\|')} | {', '.join(f'[{p}]' for p in contra.supporting_papers) or 'None'} | {', '.join(f'[{p}]' for p in contra.contradicting_papers) or 'None'} | {contra.overall_assessment.replace('|','\\|')} |")
        if not report.contradictions: md_lines.append("| No substantial empirical contradictions detected across current sample | — | — | Not enough contradictory evidence |")
        md_lines.extend(["", "## 10. Method / Approach Comparison", "| Paper ID | Title | Year | Venue | Classification / Tier | Citations | Full-text status |", "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |"])
        for comp in report.method_comparisons:
            paper = next((p for p in report.papers if p.internal_id == comp.get('paper_id')), None)
            status = paper.full_text_status if paper else "unknown"
            md_lines.append(f"| [{comp['paper_id']}] | {comp['title'].replace('|','\\|')} | {comp['year']} | {comp.get('venue') or 'Preprint'} | `{comp.get('tier')}` | {comp.get('citations',0)} | {status} |")
        md_lines.extend(["", "## 11. Limitations in Existing Research"])
        md_lines.extend(f"- {lim}" for lim in report.limitations_in_existing_research)
        md_lines.extend(["", "## 12. Classified Research Gaps"])
        for gap in report.research_gaps:
            md_lines.extend([f"### {gap.gap_id}: {gap.category.value.title()}", f"- **Description**: {gap.description}", f"- **Evidenced by**: {', '.join(f'[{e}]' for e in gap.supporting_evidence) or 'N/A'}", "- **Proposed Future Directions:"])
            md_lines.extend(f"  - {d}" for d in gap.proposed_directions)
        md_lines.extend(["", "## 13. Open Research Questions"])
        md_lines.extend(f"{i}. {q}" for i, q in enumerate(report.open_research_questions, 1))
        md_lines.extend(["", "## 14. Evidence Strength & Uncertainty Evaluation", f"{report.evidence_strength_summary}\n", "> Evidence strength is an internal epistemic heuristic, not a statistical probability.", ""])
        md_lines.extend(["## 15. Conclusion", f"{report.conclusion}\n", "## 16. References", "All citations map deterministically to retrieved records below:\n"])
        for p in report.papers:
            authors = ", ".join(p.authors[:4]) + (" et al." if len(p.authors) > 4 else "") if p.authors else "Unknown Authors"
            status = p.full_text_status.upper().replace('_', '-')
            flag = " — **ABSTRACT-ONLY**" if status != "AVAILABLE" else " — **FULL-TEXT INGESTED**"
            md_lines.append(f"- **[{p.internal_id}]** {authors}{f' ({p.year})' if p.year else ''}. **{p.title}**.{f' *{p.venue}*.' if p.venue else ''}{f' DOI: [{p.doi}](https://doi.org/{p.doi})' if p.doi else ''} `{', '.join(p.sources)}` **{status}**{flag}")
        return "\n".join(md_lines)

    def save_report(self, report: ResearchReport, output_dir: Path | None = None) -> tuple[Path, Path]:
        target_dir = output_dir or config.REPORTS_DIR
        target_dir.mkdir(parents=True, exist_ok=True)
        timestamp_slug = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        md_path, json_path = target_dir / f"research_{timestamp_slug}.md", target_dir / f"research_{timestamp_slug}.json"
        md_path.write_text(self.render_markdown(report), encoding="utf-8")
        json_path.write_text(json.dumps(report.model_dump(mode="json"), indent=2, ensure_ascii=False), encoding="utf-8")
        return md_path, json_path
