"""Report generator producing professional 16-section reports with traceable [Pxx] citations."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from app.models.schemas import ResearchReport
from app.config import config


class ReportGenerator:
    """Renders ResearchReport models into professional Markdown documents and JSON data files."""

    def render_markdown(self, report: ResearchReport) -> str:
        """Render the 16 required sections into a GitHub-flavored markdown report."""
        timestamp_str = report.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")

        md_lines = [
            f"# Academic Research Report: {report.research_question}",
            f"\n*Generated by Lightweight Academic Research Agent on {timestamp_str}*\n",
            "---\n",
            "## 1. Research Question",
            f"> **{report.research_question}**\n",
            "## 2. Executive Summary",
            f"{report.executive_summary}\n",
            "## 3. Research Methodology",
            f"{report.research_methodology}\n",
            "## 4. Academic Sources Searched",
            "The following independent academic sources and registries were queried:",
        ]
        for src in report.academic_sources_searched:
            md_lines.append(f"- **{src.replace('_', ' ').title()}**")
        md_lines.append("")

        md_lines.extend([
            "## 5. Search Strategy",
            f"{report.search_strategy_summary}\n",
            "## 6. Key Findings",
        ])
        for idx, finding in enumerate(report.key_findings, 1):
            md_lines.append(f"{idx}. {finding}")
        md_lines.append("")

        # Section 7: Evidence Table
        md_lines.extend([
            "## 7. Evidence Table",
            "| Evidence ID | Claim ID | Paper ID | Evidence Type | Strength | Extracted Excerpt |",
            "| :--- | :--- | :--- | :--- | :--- | :--- |",
        ])
        if report.evidence_records:
            for ev in report.evidence_records:
                excerpt = ev.quote_or_excerpt.replace("|", "\\|")
                if len(excerpt) > 90:
                    excerpt = excerpt[:87] + "..."
                md_lines.append(
                    f"| {ev.evidence_id} | {ev.claim_id} | [{ev.paper_id}] | {ev.evidence_type.value} | `{ev.strength.value}` | {excerpt} |"
                )
        else:
            md_lines.append("| — | — | — | — | — | No specific evidence records captured |")
        md_lines.append("")

        # Section 8: Supporting Evidence
        md_lines.extend([
            "## 8. Supporting Evidence",
            "Systematic mapping of central scientific assertions confirmed by retrieved literature:",
        ])
        supporting_claims = [c for c in report.claims if c.evidence_type.value in ("empirical result", "methodological claim", "comparison")]
        if supporting_claims:
            for c in supporting_claims:
                srcs = ", ".join(f"[{s}]" for s in c.supporting_sources) if c.supporting_sources else f"[{c.paper_id}]"
                md_lines.append(f"- **Claim ({c.evidence_type.value})**: {c.claim_text}")
                md_lines.append(f"  - **Supporting Sources**: {srcs} | **Strength**: `{c.evidence_strength.value}` | **Confidence**: {c.confidence:.2f}")
        else:
            md_lines.append("No independent empirical support records isolated.")
        md_lines.append("")

        # Section 9: Contradictory Evidence & Disagreements
        md_lines.extend([
            "## 9. Contradictory Evidence & Scientific Disagreements",
            "Active falsification and trade-off analysis across retrieved publications:",
            "| Technical Point / Claim | Supporting Papers | Contradicting / Caveat Papers | Overall Assessment |",
            "| :--- | :--- | :--- | :--- |",
        ])
        if report.contradictions:
            for contra in report.contradictions:
                claim_text = contra.claim.replace("|", "\\|")
                supp_str = ", ".join(f"[{p}]" for p in contra.supporting_papers) if contra.supporting_papers else "None"
                contra_str = ", ".join(f"[{p}]" for p in contra.contradicting_papers) if contra.contradicting_papers else "None"
                assess = contra.overall_assessment.replace("|", "\\|")
                md_lines.append(f"| {claim_text} | {supp_str} | {contra_str} | {assess} |")
        else:
            md_lines.append("| No substantial empirical contradictions detected across current sample | — | — | Literature consensus observed |")
        md_lines.append("")

        # Section 10: Method/Approach Comparison
        md_lines.extend([
            "## 10. Method / Approach Comparison",
            "| Paper ID | Title | Year | Venue | Classification / Tier | Citations |",
            "| :--- | :--- | :--- | :--- | :--- | :--- |",
        ])
        for comp in report.method_comparisons:
            t = comp['title'].replace("|", "\\|")
            if len(t) > 60:
                t = t[:57] + "..."
            md_lines.append(
                f"| [{comp['paper_id']}] | {t} | {comp['year']} | {comp.get('venue') or 'Preprint'} | `{comp.get('tier')}` | {comp.get('citations', 0)} |"
            )
        md_lines.append("")

        # Section 11: Limitations in Existing Research
        md_lines.extend([
            "## 11. Limitations in Existing Research",
        ])
        for lim in report.limitations_in_existing_research:
            md_lines.append(f"- {lim}")
        md_lines.append("")

        # Section 12: Research Gaps
        md_lines.extend([
            "## 12. Classified Research Gaps",
            "Specific, grounded unresolved challenges identified in the literature:",
        ])
        for gap in report.research_gaps:
            evidence_str = ", ".join(f"[{e}]" for e in gap.supporting_evidence) if gap.supporting_evidence else "N/A"
            md_lines.extend([
                f"### {gap.gap_id}: {gap.category.value.title()}",
                f"- **Description**: {gap.description}",
                f"- **Evidenced by**: {evidence_str}",
                "- **Proposed Future Directions**:",
            ])
            for direction in gap.proposed_directions:
                md_lines.append(f"  - {direction}")
            md_lines.append("")

        # Section 13: Open Research Questions
        md_lines.extend([
            "## 13. Open Research Questions",
        ])
        for idx, q in enumerate(report.open_research_questions, 1):
            md_lines.append(f"{idx}. {q}")
        md_lines.append("")

        # Section 14: Evidence Strength / Confidence
        md_lines.extend([
            "## 14. Evidence Strength & Uncertainty Evaluation",
            f"{report.evidence_strength_summary}\n",
            "> [!NOTE]",
            "> Evidence strength represents an internal epistemic heuristic (incorporating independent source counts, peer-review quality tiers, and conflict detection). It is not a statistical Bayesian probability.",
            "",
        ])

        # Section 15: Conclusion
        md_lines.extend([
            "## 15. Conclusion",
            f"{report.conclusion}\n",
        ])

        # Section 16: References
        md_lines.extend([
            "## 16. References",
            "All citations used in this report map deterministically to the retrieved records below:\n",
        ])
        for p in report.papers:
            authors_str = ", ".join(p.authors[:4]) + (" et al." if len(p.authors) > 4 else "") if p.authors else "Unknown Authors"
            venue_str = f" *{p.venue}*" if p.venue else ""
            year_str = f" ({p.year})" if p.year else ""
            doi_str = f" DOI: [{p.doi}](https://doi.org/{p.doi})" if p.doi else ""
            url_str = f" [Source URL]({p.url})" if p.url and not p.doi else ""
            sources_tag = f" `[{', '.join(p.sources)}]`"
            relevance_tag = f" *(Relevance: {p.relevance_score:.2f})*"

            md_lines.append(
                f"- **[{p.internal_id}]** {authors_str}{year_str}. **{p.title}**.{venue_str}.{doi_str}{url_str}{sources_tag}{relevance_tag}"
            )

        return "\n".join(md_lines)

    def save_report(
        self,
        report: ResearchReport,
        output_dir: Path | None = None,
    ) -> tuple[Path, Path]:
        """Save report as both Markdown (.md) and structured JSON (.json)."""
        target_dir = output_dir or config.REPORTS_DIR
        target_dir.mkdir(parents=True, exist_ok=True)

        timestamp_slug = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        md_path = target_dir / f"research_{timestamp_slug}.md"
        json_path = target_dir / f"research_{timestamp_slug}.json"

        # Write Markdown
        md_content = self.render_markdown(report)
        md_path.write_text(md_content, encoding="utf-8")

        # Write JSON
        json_data = report.model_dump(mode="json")
        json_path.write_text(json.dumps(json_data, indent=2, ensure_ascii=False), encoding="utf-8")

        return md_path, json_path

