"""Report generator with full-text provenance and explicit abstract-only flags."""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path
from app.models.schemas import ResearchReport
from app.config import config

class ReportGenerator:
    def render_markdown(self, report: ResearchReport) -> str:
        timestamp = report.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")
        lines = [f"# Academic Research Report: {report.research_question}", f"\n*Generated by Lightweight Academic Research Agent on {timestamp}*\n", "---", "## 1. Research Question", f"> **{report.research_question}**\n", "## 2. Executive Summary", report.executive_summary, "", "## 3. Research Methodology", report.research_methodology, "", "## 4. Academic Sources Searched"]
        lines.extend(f"- **{src.replace('_', ' ').title()}**" for src in report.academic_sources_searched)
        lines.extend(["", "## 5. Search Strategy", report.search_strategy_summary, "", "## 6. Key Findings"])
        lines.extend(f"{i}. {finding}" for i, finding in enumerate(report.key_findings, 1))
        lines.extend(["", "## 7. Evidence Table", "| Evidence ID | Claim ID | Paper ID | Type | Strength | Section | Pages | Grounding | Excerpt |", "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |"])
        if report.evidence_records:
            for ev in report.evidence_records:
                excerpt = ev.quote_or_excerpt.replace("|", "\\|")
                if len(excerpt) > 90: excerpt = excerpt[:87] + "..."
                pages = f"{ev.page_start}-{ev.page_end}" if ev.page_start else "—"
                grounding = "FULL-TEXT" if ev.full_text_grounded else "ABSTRACT-ONLY"
                lines.append(f"| {ev.evidence_id} | {ev.claim_id} | [{ev.paper_id}] | {ev.evidence_type.value} | `{ev.strength.value}` | {ev.section} | {pages} | **{grounding}** | {excerpt} |")
        else:
            lines.append("| — | — | — | — | — | — | — | — | No evidence records |")
        lines.extend(["", "## 8. Supporting Evidence"])
        for claim in report.claims:
            sources = ", ".join(f"[{s}]" for s in claim.supporting_sources) or f"[{claim.paper_id}]"
            grounding = "FULL-TEXT" if claim.section != "abstract" else "ABSTRACT-ONLY"
            lines.append(f"- **Claim ({claim.evidence_type.value}; {grounding})**: {claim.claim_text}")
            lines.append(f"  - Sources: {sources} | Section: {claim.section} | Pages: {claim.page_start or '—'}-{claim.page_end or '—'} | Strength: `{claim.evidence_strength.value}` | Confidence: {claim.confidence:.2f}")
        lines.extend(["", "## 9. Contradictory Evidence & Scientific Disagreements", "| Technical Point / Claim | Supporting Papers | Contradicting / Caveat Papers | Overall Assessment |", "| :--- | :--- | :--- | :--- |"])
        for contra in report.contradictions:
            claim_text = contra.claim.replace("|", "\\|")
            support = ", ".join(f"[{p}]" for p in contra.supporting_papers) or "None"
            oppose = ", ".join(f"[{p}]" for p in contra.contradicting_papers) or "None"
            assessment = contra.overall_assessment.replace("|", "\\|")
            lines.append(f"| {claim_text} | {support} | {oppose} | {assessment} |")
        if not report.contradictions: lines.append("| No substantial contradictions detected across current sample | — | — | Not enough contradictory evidence |")
        lines.extend(["", "## 10. Method / Approach Comparison", "| Paper ID | Title | Year | Venue | Tier | Citations | Full-text status |", "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |"])
        for comp in report.method_comparisons:
            title = str(comp.get("title", "")).replace("|", "\\|")
            paper = next((p for p in report.papers if p.internal_id == comp.get("paper_id")), None)
            status = paper.full_text_status if paper else "unknown"
            lines.append(f"| [{comp.get('paper_id')}] | {title} | {comp.get('year','—')} | {comp.get('venue') or 'Preprint'} | `{comp.get('tier','—')}` | {comp.get('citations',0)} | {status} |")
        lines.extend(["", "## 11. Limitations in Existing Research"])
        lines.extend(f"- {lim}" for lim in report.limitations_in_existing_research)
        lines.extend(["", "## 12. Classified Research Gaps"])
        for gap in report.research_gaps:
            evidence = ", ".join(f"[{e}]" for e in gap.supporting_evidence) or "N/A"
            lines.extend([f"### {gap.gap_id}: {gap.category.value.title()}", f"- Description: {gap.description}", f"- Evidenced by: {evidence}", "- Proposed Future Directions:"])
            lines.extend(f"  - {direction}" for direction in gap.proposed_directions)
        lines.extend(["", "## 13. Open Research Questions"])
        lines.extend(f"{i}. {question}" for i, question in enumerate(report.open_research_questions, 1))
        lines.extend(["", "## 14. Evidence Strength & Uncertainty Evaluation", report.evidence_strength_summary, "> Evidence strength is an internal epistemic heuristic, not a statistical probability.", "", "## 15. Conclusion", report.conclusion, "", "## 16. References", "All citations map deterministically to retrieved records below:", ""])
        for paper in report.papers:
            authors = ", ".join(paper.authors[:4]) + (" et al." if len(paper.authors) > 4 else "") if paper.authors else "Unknown Authors"
            status = paper.full_text_status.upper().replace("_", "-")
            flag = "FULL-TEXT INGESTED" if status == "AVAILABLE" else "ABSTRACT-ONLY"
            lines.append(f"- **[{paper.internal_id}]** {authors}{f' ({paper.year})' if paper.year else ''}. **{paper.title}**. {paper.venue or 'Preprint'}. `{', '.join(paper.sources)}` **{flag}**")
        return "\n".join(lines)

    def save_report(self, report: ResearchReport, output_dir: Path | None = None) -> tuple[Path, Path]:
        target = output_dir or config.REPORTS_DIR
        target.mkdir(parents=True, exist_ok=True)
        slug = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        md_path, json_path = target / f"research_{slug}.md", target / f"research_{slug}.json"
        md_path.write_text(self.render_markdown(report), encoding="utf-8")
        json_path.write_text(json.dumps(report.model_dump(mode="json"), indent=2, ensure_ascii=False), encoding="utf-8")
        return md_path, json_path
